export const DefaultHead = () => {
    return (
        <>
            <meta charSet="UTF-8" />

            <meta name="author" content="Swizec Teller" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1.0"
            />
            <link
                rel="apple-touch-icon"
                sizes="180x180"
                href="/apple-touch-icon.png"
            />
            <link
                rel="icon"
                type="image/png"
                sizes="32x32"
                href="/favicon-32x32.png"
            />
            <link
                rel="icon"
                type="image/png"
                sizes="16x16"
                href="/favicon-16x16.png"
            />
            <link rel="manifest" href="/site.webmanifest" />

            <meta name="title" content="ScholarStream.ai" />
            <meta
                name="description"
                content="Latest research from the world of academia, all in a convenient and engaging Twitter-like feed generated by AI."
            />

            <meta property="og:type" content="website" />
            <meta property="og:url" content="https://www.scholarstream.ai/" />
            <meta property="og:title" content="ScholarStream.ai" />
            <meta
                property="og:description"
                content="Latest research from the world of academia, all in a convenient and engaging Twitter-like feed generated by AI."
            />
            <meta property="og:image" content="/opengraph.png" />

            <meta property="twitter:card" content="summary_large_image" />
            <meta
                property="twitter:url"
                content="https://www.scholarstream.ai/"
            />
            <meta property="twitter:title" content="ScholarStream.ai" />
            <meta
                property="twitter:description"
                content="Latest research from the world of academia, all in a convenient and engaging Twitter-like feed generated by AI."
            />
            <meta property="twitter:image" content="/opengraph.png" />
        </>
    );
};

export default function Head({ params }: { params: { topic: string } }) {
    return (
        <>
            <title>ScholarStream.ai</title>
            <DefaultHead />
        </>
    );
}
